import LocalizedStrings from 'react-localization';

export default new LocalizedStrings({
    en: {
        "Cabinet": "Cabinet",
        "Administration": "Administration",
        "Laboratory": "Laboratory",
        "Weighing": "Weighing",
        "Profile": "Profile",
        "Register": "Register",
        "Log out": "Log out",
        "Log in": "Log in",
        "Providing": "Providing",
        "Registration": "Registration",
        "Provider registration": "Provider registration",
        "username": "Login",
        "password1": "Password",
        "password2": "Confirm password",
        "email": "Email",
        "phone": "Phone",
        "first_name": "First name",
        "last_name": "Last name",
        "Login": "Login",
        "password": "Password",
        "Confirm provider registration": "Confirm provider registration",
        "Confirm": "Confirm",
        "Cancel": "Cancel",
        "Elevators management": "Elevators management",
        "Creation": "Creation",
        "Create": "Create",
        "Deletion": "Deletion",
        "Delete": "Delete",
        "Editing": "Editing",
        "Edit": "Edit",
        "name": "name",
        "address": "address",
        "Loading data from server...": "Loading data from server...",
        "Are you sure you want to delete": "Are you sure you want to delete",
        "Goods management": "Goods management",
        "middle_name": "Middle name",
        "Laboratory assistants management": "Laboratory assistants management",
        "Weighings management": "Weighings management",
        "Providers management": "Providers management",
        "Guardians management": "Guardians management",
        "Admins management": "Admins management",
        "user": "User login",
        "elevator": "Elevator name",
        "from": "from",
        "Contracts management": "Contracts management",
        "Waybills management": "Waybills management",
        "kg": "kg",
        "good": "Good name",
        "total_weight": "total_weight",
        "date": "date",
        "humidity": "Humidity",
        "clogging": "Clogging",
        "net_weight": "Net",
        "gross_weight": "Gross",
        "contract": "Contract name",
        "departure_time": "Departure time",
        "arrival_time": "Arrival time",
        "Weight check": "Weight check",
        "Laboratory analysis": "Laboratory analysis",
        "Laboratory assistant": "Laboratory assistant",
        "LSD management": "LSD management",
        "Logging out": "Logging out",
        "Connecting to server...": "Connecting to server...",
        "Users management": "Users management",
        "is_superuser": "Is superuser?",
        "provider": "Provider name",
        "to_elevator": "To elevator?",
        "LSD name": "LSD name",
        "Motion report and balances": "Motion report and balances",
    },
    ru: {
        "Cabinet": "Кабинет",
        "Administration": "Администрирование",
        "Laboratory": "Лаборатория",
        "Weighing": "Весовая",
        "Profile": "Профиль",
        "Register": "Зарегистрироватся",
        "Log out": "Выйти",
        "Log in": "Войти",
        "Providing": "Поставки",
        "Registration": "Регистрация",
        "Provider registration": "Регистрация поставщика",
        "username": "Логин",
        "password1": "Пароль",
        "password2": "Подтверждающий пароль",
        "email": "Email",
        "phone": "Телефон",
        "first_name": "Имя",
        "last_name": "Фамилия",
        "Login": "Вход",
        "password": "Пароль",
        "Confirm provider registration": "Подтвердить регистрацию поставщика",
        "Confirm": "Подтвердить",
        "Cancel": "Отменить",
        "Elevators management": "Управление элеваторами",
        "Creation": "Создание",
        "Create": "Создать",
        "Deletion": "Удаление",
        "Delete": "Удалить",
        "Editing": "Изменение",
        "Edit": "Изменить",
        "name": "Название",
        "address": "Адрес",
        "Loading data from server...": "Загрузка данных из сервера...",
        "Are you sure you want to delete": "Вы уверены, что хотите удалить",
        "Goods management": "Управление товарами",
        "middle_name": "Отчество",
        "Laboratory assistants management": "Управление лаборантами",
        "Weighings management": "Управление весовщиками",
        "Providers management": "Управление поставщиками",
        "Guardians management": "Управление охранниками",
        "Admins management": "Управление администраторами",
        "user": "Логин пользователя",
        "elevator": "Имя элеватора",
        "from": "с",
        "Contracts management": "Управление договорами",
        "Waybills management": "Управление накладными",
        "kg": "кг",
        "good": "Наименование товара",
        "total_weight": "Общий вес нетто",
        "date": "Дата начала",
        "humidity": "Влажность",
        "clogging": "Ссорность",
        "net_weight": "Нетто",
        "gross_weight": "Брутто",
        "contract": "Название договора",
        "departure_time": "Время отправки",
        "arrival_time": "Время прибытия",
        "Weight check": "Взвешивание",
        "Laboratory analysis": "Лабораторный анализ",
        "Laboratory assistant": "Лабораторант",
        "LSD management": "Упраление ТТН",
        "Logging out": "Выход...",
        "Connecting to server...": "Подключение к серверу...",
        "Users management": "Управление пользователями",
        "is_superuser": "Администратор?",
        "provider": "Название поставщика",
        "to_elevator": "К елеватору?",
        "LSD name": "Название ТТН",
        "Motion report and balances": "Отчет по движению и остаткам",
    },
    uk: {
        "Cabinet": "Кабінет",
        "Administration": "Адміністрування",
        "Laboratory": "Лабораторія",
        "Weighing": "Вагова",
        "Profile": "Профіль",
        "Register": "Зареєструватися",
        "Log out": "Вийти",
        "Log in": "Увійти",
        "Providing": "Поставки",
        "Registration": "Реєстрація",
        "Provider registration": "Реєстрація постачальника",
        "username": "Логін",
        "password1": "Пароль",
        "password2": "Підтвердження паролю",
        "email": "Email",
        "phone": "Телефон",
        "first_name": "Ім'я",
        "last_name": "Прізвище",
        "Login": "Вхід",
        "password": "Пароль",
        "Confirm provider registration": "Підтвердити реєстрацію постачальника",
        "Confirm": "Підтвердити",
        "Cancel": "Скасувати",
        "Elevators management": "Управління елеваторами",
        "Creation": "Створення",
        "Create": "Створити",
        "Deletion": "Видалення",
        "Delete": "Видалити",
        "Editing": "Редагування",
        "Edit": "Редагувати",
        "name": "Назва",
        "address": "Адреса",
        "Loading data from server...": "Завантаження даних із сервера",
        "Are you sure you want to delete": "Ви впевнені, що бажаєте видалити",
        "Goods management": "Управління товарами",
        "middle_name": "По-батькові",
        "Laboratory assistants management": "Управління лаборантами",
        "Weighings management": "Управління ваговими",
        "Providers management": "Управління постачальниками",
        "Guardians management": "Управління охоронцями",
        "Admins management": "Управління адміністраторами",
        "user": "Логін користувача",
        "elevator": "Назва елеватора",
        "from": "з",
        "Contracts management": "Управління договорами",
        "Waybills management": "Управління накладними",
        "kg": "кг",
        "good": "Назва товару",
        "total_weight": "Загальна вага нетто",
        "date": "Дата початку дії",
        "humidity": "Вологість",
        "clogging": "Засміченість",
        "net_weight": "Нетто",
        "gross_weight": "Брутто",
        "contract": "Назва договору",
        "departure_time": "Час відправлення",
        "arrival_time": "Час прибуття",
        "Weight check": "Зважування",
        "Laboratory analysis": "Лабораторний аналіз",
        "Laboratory assistant": "Лаборант",
        "LSD management": "Управління ТТН",
        "Logging out": "Вихід...",
        "Connecting to server...": "Підключення до сервера...",
        "Users management": "Управління користувачами",
        "is_superuser": "Адміністратор?",
        "provider": "Назва постачальника",
        "to_elevator": "До елеватора?",
        "LSD name": "Назва ТТН",
        "Motion report and balances": "Звіт за рухом і залишками",
    }
});