# Generated by Django 3.0.3 on 2020-02-12 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='elevator',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('user', 'elevator')},
        ),
        migrations.AlterUniqueTogether(
            name='labassistant',
            unique_together={('user', 'elevator')},
        ),
        migrations.AlterUniqueTogether(
            name='weighing',
            unique_together={('user', 'elevator')},
        ),
    ]
