# Generated by Django 3.0.3 on 2020-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_auto_20200212_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='to_elevator',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
