# Generated by Django 3.0.3 on 2020-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_auto_20200212_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightcheck',
            name='gross_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weightcheck',
            name='net_weight',
            field=models.FloatField(null=True),
        ),
    ]
