# Generated by Django 3.0.3 on 2020-02-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0007_auto_20200212_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='lab_analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elevator.LabAnalysis'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elevator.WeightCheck'),
        ),
    ]
