# Generated by Django 3.0.3 on 2020-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0008_auto_20200212_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labanalysis',
            name='clogging',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='labanalysis',
            name='humidity',
            field=models.FloatField(null=True),
        ),
    ]
