# Generated by Django 3.0.3 on 2020-02-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0010_auto_20200219_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_lsd_unhurted',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='lsd_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='to_elevator',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='trailer_number',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='GuardianDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('car_number', models.TextField(max_length=200)),
                ('trailer_number', models.TextField(max_length=200, null=True)),
                ('driver_name', models.TextField(max_length=200)),
                ('to_elevator', models.BooleanField(default=False)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.Elevator')),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elevator.Guardian')),
            ],
        ),
        migrations.AlterField(
            model_name='lsd',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsds', to='elevator.GuardianDelivery'),
        ),
    ]
