# Generated by Django 3.0.3 on 2020-02-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0011_auto_20200219_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsd',
            old_name='delivery',
            new_name='guardian_delivery',
        ),
    ]
