# Generated by Django 3.0.3 on 2020-02-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0012_auto_20200219_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='to_elevator',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guardiandelivery',
            name='to_elevator',
            field=models.BooleanField(default=True),
        ),
    ]
